[build]
  command = "npm run build"
  publish = "dist/client"
  functions = "netlify/functions"

[dev]
  command = "npm run dev:netlify"
  targetPort = 5000
  port = 8888
  publish = "dist/client"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200